name: Fill Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        shell: pwsh
        run: |
          
          # Download installer
          $workspace = "${{ github.workspace }}"
          Invoke-WebRequest -Uri "${{ secrets.DOWNLOAD_URL }}" -OutFile "$workspace/install.exe"
          
          if (Test-Path "$workspace/install.exe") {
            Write-Host "Installer downloaded successfully."
            $fileSize = (Get-Item "$workspace/install.exe").Length
            Write-Host "Installer size: $fileSize bytes."
          } else {
            Write-Error "Installer download failed."
            exit 1
          } 

          # Run installer with parameters
          Start-Process -FilePath "$workspace/install.exe" -ArgumentList "-s1", "-lic=${{ secrets.LICENCE }}", "-email=${{ secrets.EMAIL }}" -Wait -PassThru

      - name: Run tests
        shell: pwsh
        run: |
          # Test command line via Python piped json 
          python "${{ github.workspace }}/source/ccw.py"
          
          # Test direct command line
          & 'C:/Program Files (x86)/Crossword Compiler/ccw.exe' -c "${{ github.workspace }}/tests/fill.json"

      - name: Check Puzzle Files
        shell: pwsh
        run: |
          $puzzleFiles = Get-ChildItem -Path "${{ github.workspace }}/tests" -Filter *.puz
          
          # Check if any files exist
          if ($puzzleFiles.Count -eq 0) {
            Write-Error "No puzzle files generated"
            exit 1
          }
          
          # List files with details
          Write-Host "Puzzle Files Found:"
          $puzzleFiles | Format-Table Name, Length, LastWriteTime 

      - name: Upload Puzzle File
        uses: actions/upload-artifact@v4
        with:
          name: puzzle-files
          path: ${{ github.workspace }}/tests/*.puz